
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lahiru Madushan
 */
public class Addpgstd extends javax.swing.JFrame {

    /**
     * Creates new form Addpgstd
     */
    pgstudent std = new pgstudent();
    public Addpgstd() {
        initComponents();
        ButtonGroup bg4 = new ButtonGroup();
        bg4.add(pgstdsoc);
        bg4.add(pgstdsoe);
        bg4.add(pgstdsom);
        pgstdsoc.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        res1a = new javax.swing.JRadioButton();
        res1b = new javax.swing.JRadioButton();
        res1c = new javax.swing.JRadioButton();
        res1s = new javax.swing.JRadioButton();
        res2s = new javax.swing.JRadioButton();
        res2c = new javax.swing.JRadioButton();
        res2b = new javax.swing.JRadioButton();
        res2a = new javax.swing.JRadioButton();
        res3a = new javax.swing.JRadioButton();
        res3b = new javax.swing.JRadioButton();
        res3c = new javax.swing.JRadioButton();
        res3s = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pgstdid = new javax.swing.JTextField();
        pgstdname = new javax.swing.JTextField();
        pgstdtp = new javax.swing.JTextField();
        pgstdaddres = new javax.swing.JTextField();
        pgstdnic = new javax.swing.JTextField();
        pgstdyears = new javax.swing.JTextField();
        pgstdacayear = new javax.swing.JTextField();
        pgstdsoc = new javax.swing.JRadioButton();
        pgstdsoe = new javax.swing.JRadioButton();
        pgstdsom = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddPGStudent = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        pgstdemail = new javax.swing.JTextField();
        pgstddob = new javax.swing.JTextField();
        pgstddegree = new javax.swing.JTextField();
        pgstdinstitute = new javax.swing.JTextField();

        res1a.setBackground(new java.awt.Color(51, 255, 204));
        res1a.setText("A");
        res1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res1aActionPerformed(evt);
            }
        });

        res1b.setBackground(new java.awt.Color(51, 255, 204));
        res1b.setText("B");

        res1c.setBackground(new java.awt.Color(51, 255, 204));
        res1c.setText("C");

        res1s.setBackground(new java.awt.Color(51, 255, 204));
        res1s.setText("S");

        res2s.setBackground(new java.awt.Color(51, 255, 204));
        res2s.setText("S");

        res2c.setBackground(new java.awt.Color(51, 255, 204));
        res2c.setText("C");

        res2b.setBackground(new java.awt.Color(51, 255, 204));
        res2b.setText("B");

        res2a.setBackground(new java.awt.Color(51, 255, 204));
        res2a.setText("A");
        res2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res2aActionPerformed(evt);
            }
        });

        res3a.setBackground(new java.awt.Color(51, 255, 204));
        res3a.setText("A");
        res3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res3aActionPerformed(evt);
            }
        });

        res3b.setBackground(new java.awt.Color(51, 255, 204));
        res3b.setText("B");

        res3c.setBackground(new java.awt.Color(51, 255, 204));
        res3c.setText("C");

        res3s.setBackground(new java.awt.Color(51, 255, 204));
        res3s.setText("S");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel2.setText("ID :");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setText("Full Name :");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setText("NIC :");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New PG Student");

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel7.setText("Addres :");

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel8.setText("Tel No:");

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel9.setText("DOB :");

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel10.setText("Institute :");

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel11.setText("Degree :");

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel13.setText("Years :");

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel14.setText("Aca Year :");

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel15.setText("Faculty :");

        pgstdid.setBackground(new java.awt.Color(51, 255, 204));
        pgstdid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgstdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstdidActionPerformed(evt);
            }
        });

        pgstdname.setBackground(new java.awt.Color(51, 255, 204));
        pgstdname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgstdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstdnameActionPerformed(evt);
            }
        });

        pgstdtp.setBackground(new java.awt.Color(51, 255, 204));
        pgstdtp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgstdtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstdtpActionPerformed(evt);
            }
        });
        pgstdtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pgstdtpKeyTyped(evt);
            }
        });

        pgstdaddres.setBackground(new java.awt.Color(51, 255, 204));
        pgstdaddres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgstdaddres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstdaddresActionPerformed(evt);
            }
        });

        pgstdnic.setBackground(new java.awt.Color(51, 255, 204));
        pgstdnic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgstdnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstdnicActionPerformed(evt);
            }
        });

        pgstdyears.setBackground(new java.awt.Color(51, 255, 204));
        pgstdyears.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstdyearsActionPerformed(evt);
            }
        });

        pgstdacayear.setBackground(new java.awt.Color(51, 255, 204));
        pgstdacayear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstdacayearActionPerformed(evt);
            }
        });

        pgstdsoc.setBackground(new java.awt.Color(51, 255, 204));
        pgstdsoc.setText("SOC");

        pgstdsoe.setBackground(new java.awt.Color(51, 255, 204));
        pgstdsoe.setText("SOE");
        pgstdsoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstdsoeActionPerformed(evt);
            }
        });

        pgstdsom.setBackground(new java.awt.Color(51, 255, 204));
        pgstdsom.setText("SOM");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nsbm-green-uni-logo.png"))); // NOI18N

        jButtonAddPGStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddPGStudent.setText("Submit");
        jButtonAddPGStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPGStudentActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel16.setText("Email :");

        pgstdemail.setBackground(new java.awt.Color(51, 255, 204));

        pgstddob.setBackground(new java.awt.Color(51, 255, 204));
        pgstddob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgstddob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstddobActionPerformed(evt);
            }
        });
        pgstddob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pgstddobKeyTyped(evt);
            }
        });

        pgstddegree.setBackground(new java.awt.Color(51, 255, 204));
        pgstddegree.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgstddegree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstddegreeActionPerformed(evt);
            }
        });
        pgstddegree.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pgstddegreeKeyTyped(evt);
            }
        });

        pgstdinstitute.setBackground(new java.awt.Color(51, 255, 204));
        pgstdinstitute.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pgstdinstitute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pgstdinstituteActionPerformed(evt);
            }
        });
        pgstdinstitute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pgstdinstituteKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(105, 232, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pgstdname)
                                            .addComponent(pgstdemail)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(pgstdnic, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgstdtp, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgstdaddres, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgstddob, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgstddegree, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgstdinstitute, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgstdyears, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(pgstdsoc)
                                                    .addComponent(pgstdacayear, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(24, 24, 24)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonCancel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonAddPGStudent))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(pgstdsoe)
                                        .addGap(18, 18, 18)
                                        .addComponent(pgstdsom)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pgstdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pgstdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pgstdnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(pgstdemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(pgstdaddres, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(pgstdtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pgstddob, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(pgstddegree, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(pgstdinstitute, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pgstdyears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(pgstdsoc)
                    .addComponent(pgstdsoe)
                    .addComponent(pgstdsom))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(pgstdacayear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddPGStudent)
                    .addComponent(jButtonCancel))
                .addGap(3, 3, 3)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pgstddobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pgstddobKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstddobKeyTyped

    private void pgstddobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstddobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstddobActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    public boolean verifText(){
        if(pgstdid.getText().equals("") || pgstdname.getText().equals("") || pgstdnic.getText().equals("") || pgstdemail.getText().equals("") || pgstdaddres.getText().equals("") || pgstdtp.getText().equals("") || pgstddob.getText().equals("")|| pgstddegree.getText().equals("")||pgstdinstitute.getText().equals("")||pgstdyears.getText().equals("")|| pgstdacayear.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Some fields are empty!!!");
            return false;
        }
        else{
            return true;
        }
    }
    private void jButtonAddPGStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPGStudentActionPerformed
        // add ug std btn
        String id = pgstdid.getText();
        String name = pgstdname.getText();
        String nic = pgstdnic.getText();
        String email = pgstdemail.getText();
        String addres = pgstdaddres.getText();
        String Phone = pgstdtp.getText();
        String dob = pgstddob.getText();
        String degree = pgstddegree.getText();
        String institute = pgstdinstitute.getText();
        
        

        String years = pgstdyears.getText();

        String faculty = "SOC";
        if(pgstdsoe.isSelected()){
            faculty = "SOE";
        }else if(pgstdsom.isSelected()){
            faculty = "SOM";
        }

        String acayear = pgstdacayear.getText();

        if(verifText()){
            pgstudent pgstd = new pgstudent();
            pgstd.insertUpdateDeletePGStudent('i', id, name, nic, email, addres, Phone, dob, degree, institute, years, faculty, acayear);
            MainForm.jLabel_pgstdcount.setText("PG Student Count = "+Integer.toString( MyFunction.countData("postgradstd")));
            MainForm.jLabel_sompg.setText("SOM PG Student Count = "+Integer.toString( MyFunction.countsompg("postgradstd")));
            MainForm.jLabel_socpg.setText("SOC PG Student Count = "+Integer.toString( MyFunction.countsocpg("postgradstd")));
            MainForm.jLabel_soepg.setText("SOE PG Student Count = "+Integer.toString( MyFunction.countsoepg("postgradstd")));
            ManagePGstd.jTable.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","NIC","Email","Address","Phone","DOB","Degree","Institute","Years","Faculty","Aca year"}));
            std.fillStudentJtable(ManagePGstd.jTable, "");
        }
    }//GEN-LAST:event_jButtonAddPGStudentActionPerformed

    private void res3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res3aActionPerformed

    private void res2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res2aActionPerformed

    private void res1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res1aActionPerformed

    private void pgstdsoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstdsoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstdsoeActionPerformed

    private void pgstdacayearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstdacayearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstdacayearActionPerformed

    private void pgstdyearsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstdyearsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstdyearsActionPerformed

    private void pgstdnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstdnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstdnicActionPerformed

    private void pgstdaddresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstdaddresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstdaddresActionPerformed

    private void pgstdtpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pgstdtpKeyTyped
        // allow only numbers

        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_pgstdtpKeyTyped

    private void pgstdtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstdtpActionPerformed

    }//GEN-LAST:event_pgstdtpActionPerformed

    private void pgstdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstdnameActionPerformed

    private void pgstdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstdidActionPerformed

    private void pgstddegreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstddegreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstddegreeActionPerformed

    private void pgstddegreeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pgstddegreeKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstddegreeKeyTyped

    private void pgstdinstituteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pgstdinstituteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstdinstituteActionPerformed

    private void pgstdinstituteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pgstdinstituteKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pgstdinstituteKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addpgstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addpgstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addpgstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addpgstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addpgstd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPGStudent;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField pgstdacayear;
    private javax.swing.JTextField pgstdaddres;
    private javax.swing.JTextField pgstddegree;
    private javax.swing.JTextField pgstddob;
    private javax.swing.JTextField pgstdemail;
    private javax.swing.JTextField pgstdid;
    private javax.swing.JTextField pgstdinstitute;
    private javax.swing.JTextField pgstdname;
    private javax.swing.JTextField pgstdnic;
    private javax.swing.JRadioButton pgstdsoc;
    private javax.swing.JRadioButton pgstdsoe;
    private javax.swing.JRadioButton pgstdsom;
    private javax.swing.JTextField pgstdtp;
    private javax.swing.JTextField pgstdyears;
    private javax.swing.JRadioButton res1a;
    private javax.swing.JRadioButton res1b;
    private javax.swing.JRadioButton res1c;
    private javax.swing.JRadioButton res1s;
    private javax.swing.JRadioButton res2a;
    private javax.swing.JRadioButton res2b;
    private javax.swing.JRadioButton res2c;
    private javax.swing.JRadioButton res2s;
    private javax.swing.JRadioButton res3a;
    private javax.swing.JRadioButton res3b;
    private javax.swing.JRadioButton res3c;
    private javax.swing.JRadioButton res3s;
    // End of variables declaration//GEN-END:variables
}
