
import java.text.SimpleDateFormat;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lahiru Madushan
 */
public class Addugstd extends javax.swing.JFrame {

    /**
     * Creates new form Addugstd
     */
    ugstudent std = new ugstudent();
    public Addugstd() {
        initComponents();
        ButtonGroup bg1 = new ButtonGroup();
        bg1.add(res1a);
        bg1.add(res1b);
        bg1.add(res1c);
        bg1.add(res1s);
        res1a.setSelected(true);
        
        ButtonGroup bg2 = new ButtonGroup();
        bg2.add(res2a);
        bg2.add(res2b);
        bg2.add(res2c);
        bg2.add(res2s);
        res2a.setSelected(true);
        
        ButtonGroup bg3 = new ButtonGroup();
        bg3.add(res3a);
        bg3.add(res3b);
        bg3.add(res3c);
        bg3.add(res3s);
        res3a.setSelected(true);
        
        ButtonGroup bg4 = new ButtonGroup();
        bg4.add(ugstdsoc);
        bg4.add(ugstdsoe);
        bg4.add(ugstdsom);
        ugstdsoc.setSelected(true);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ugstdid = new javax.swing.JTextField();
        ugstdname = new javax.swing.JTextField();
        ugstdtp = new javax.swing.JTextField();
        ugstdaddres = new javax.swing.JTextField();
        ugstdnic = new javax.swing.JTextField();
        ugstdrank = new javax.swing.JTextField();
        ugstdacayear = new javax.swing.JTextField();
        ugstdsoc = new javax.swing.JRadioButton();
        ugstdsoe = new javax.swing.JRadioButton();
        ugstdsom = new javax.swing.JRadioButton();
        res1a = new javax.swing.JRadioButton();
        res1b = new javax.swing.JRadioButton();
        res1c = new javax.swing.JRadioButton();
        res1s = new javax.swing.JRadioButton();
        res2c = new javax.swing.JRadioButton();
        res2s = new javax.swing.JRadioButton();
        res2a = new javax.swing.JRadioButton();
        res2b = new javax.swing.JRadioButton();
        res3c = new javax.swing.JRadioButton();
        res3s = new javax.swing.JRadioButton();
        res3a = new javax.swing.JRadioButton();
        res3b = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAddUGStudent = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ugstdemail = new javax.swing.JTextField();
        ugstddob = new javax.swing.JTextField();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel2.setText("ID :");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setText("Full Name :");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setText("NIC :");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("New Ug Student");

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel7.setText("Addres :");

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel8.setText("Tel No:");

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel9.setText("DOB :");

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel10.setText("A/L Res 2 :");

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel11.setText("A/L Res 1 :");

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel12.setText("A/L Res 3 :");

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel13.setText("A/L Rank :");

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel14.setText("Aca Year :");

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel15.setText("Faculty :");

        ugstdid.setBackground(new java.awt.Color(51, 255, 204));
        ugstdid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ugstdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdidActionPerformed(evt);
            }
        });

        ugstdname.setBackground(new java.awt.Color(51, 255, 204));
        ugstdname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ugstdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdnameActionPerformed(evt);
            }
        });

        ugstdtp.setBackground(new java.awt.Color(51, 255, 204));
        ugstdtp.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ugstdtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdtpActionPerformed(evt);
            }
        });
        ugstdtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ugstdtpKeyTyped(evt);
            }
        });

        ugstdaddres.setBackground(new java.awt.Color(51, 255, 204));
        ugstdaddres.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ugstdaddres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdaddresActionPerformed(evt);
            }
        });

        ugstdnic.setBackground(new java.awt.Color(51, 255, 204));
        ugstdnic.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ugstdnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdnicActionPerformed(evt);
            }
        });

        ugstdrank.setBackground(new java.awt.Color(51, 255, 204));
        ugstdrank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdrankActionPerformed(evt);
            }
        });

        ugstdacayear.setBackground(new java.awt.Color(51, 255, 204));
        ugstdacayear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdacayearActionPerformed(evt);
            }
        });

        ugstdsoc.setBackground(new java.awt.Color(51, 255, 204));
        ugstdsoc.setText("SOC");

        ugstdsoe.setBackground(new java.awt.Color(51, 255, 204));
        ugstdsoe.setText("SOE");
        ugstdsoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdsoeActionPerformed(evt);
            }
        });

        ugstdsom.setBackground(new java.awt.Color(51, 255, 204));
        ugstdsom.setText("SOM");

        res1a.setBackground(new java.awt.Color(51, 255, 204));
        res1a.setText("A");
        res1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res1aActionPerformed(evt);
            }
        });

        res1b.setBackground(new java.awt.Color(51, 255, 204));
        res1b.setText("B");

        res1c.setBackground(new java.awt.Color(51, 255, 204));
        res1c.setText("C");

        res1s.setBackground(new java.awt.Color(51, 255, 204));
        res1s.setText("S");

        res2c.setBackground(new java.awt.Color(51, 255, 204));
        res2c.setText("C");

        res2s.setBackground(new java.awt.Color(51, 255, 204));
        res2s.setText("S");

        res2a.setBackground(new java.awt.Color(51, 255, 204));
        res2a.setText("A");
        res2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res2aActionPerformed(evt);
            }
        });

        res2b.setBackground(new java.awt.Color(51, 255, 204));
        res2b.setText("B");

        res3c.setBackground(new java.awt.Color(51, 255, 204));
        res3c.setText("C");

        res3s.setBackground(new java.awt.Color(51, 255, 204));
        res3s.setText("S");

        res3a.setBackground(new java.awt.Color(51, 255, 204));
        res3a.setText("A");
        res3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res3aActionPerformed(evt);
            }
        });

        res3b.setBackground(new java.awt.Color(51, 255, 204));
        res3b.setText("B");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nsbm-green-uni-logo.png"))); // NOI18N

        jButtonAddUGStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonAddUGStudent.setText("Submit");
        jButtonAddUGStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUGStudentActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel16.setText("Email :");

        ugstdemail.setBackground(new java.awt.Color(51, 255, 204));

        ugstddob.setBackground(new java.awt.Color(51, 255, 204));
        ugstddob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ugstddob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstddobActionPerformed(evt);
            }
        });
        ugstddob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ugstddobKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel6))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ugstdnic, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ugstdrank, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ugstdacayear, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ugstdname)
                            .addComponent(ugstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ugstdtp, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ugstdaddres, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(res3a)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(res3b)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(res3c)
                                    .addGap(4, 4, 4)
                                    .addComponent(res3s))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(res2a)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(res2b)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(res2c)
                                    .addGap(4, 4, 4)
                                    .addComponent(res2s)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonCancel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonAddUGStudent))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ugstdsoc)
                                    .addGap(18, 18, 18)
                                    .addComponent(ugstdsoe)
                                    .addGap(18, 18, 18)
                                    .addComponent(ugstdsom)))
                            .addComponent(ugstdemail, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(res1a)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(res1b)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(res1c)
                                .addGap(4, 4, 4)
                                .addComponent(res1s))
                            .addComponent(ugstddob, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ugstdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ugstdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ugstdnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(ugstdemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ugstdaddres, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(ugstdtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(ugstddob, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(res1a)
                    .addComponent(res1b)
                    .addComponent(res1c)
                    .addComponent(res1s))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(res2a)
                    .addComponent(res2b)
                    .addComponent(res2c)
                    .addComponent(res2s))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(res3a)
                    .addComponent(res3b)
                    .addComponent(res3c)
                    .addComponent(res3s))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(ugstdrank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(ugstdsoc)
                    .addComponent(ugstdsoe)
                    .addComponent(ugstdsom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(ugstdacayear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonAddUGStudent)
                        .addComponent(jButtonCancel)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    public boolean verifText(){
        if(ugstdid.getText().equals("") || ugstdname.getText().equals("") || ugstdnic.getText().equals("") || ugstdemail.getText().equals("") || ugstdaddres.getText().equals("") || ugstdtp.getText().equals("") || ugstddob.getText().equals("") || ugstdrank.getText().equals("") || ugstdacayear.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Some fields are empty!!!");
            return false;
        }
        else{
            return true;
        }
    } 
    
    
    private void jButtonAddUGStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUGStudentActionPerformed
        // add ug std btn
        String id = ugstdid.getText();
        String name = ugstdname.getText();
        String nic = ugstdnic.getText();
        String email = ugstdemail.getText();
        String addres = ugstdaddres.getText();
        String Phone = ugstdtp.getText();
        String dob = ugstddob.getText();
        
        String alres1 = "A";
        if(res1b.isSelected()){
            alres1 = "B";
        }else if(res1c.isSelected()){
            alres1 = "C";
        }else if(res1s.isSelected()){
            alres1 = "S";
        }
        
        String alres2 = "A";
        if(res2b.isSelected()){
            alres2 = "B";
        }else if(res2c.isSelected()){
            alres2 = "C";
        }else if(res2s.isSelected()){
            alres2 = "S";
        }
        
        String alres3 = "A";
        if(res3b.isSelected()){
            alres3 = "B";
        }else if(res3c.isSelected()){
            alres3 = "C";
        }else if(res3s.isSelected()){
            alres3 = "S";
        }
        
        String alrank = ugstdrank.getText();
        
        String faculty = "SOC";
        if(ugstdsoe.isSelected()){
            faculty = "SOE";
        }else if(ugstdsom.isSelected()){
            faculty = "SOM";
        }
        
        String acayear = ugstdacayear.getText();
        
        if(verifText()){
        ugstudent ugstd = new ugstudent();
        ugstd.insertUpdateDeleteUGStudent('i', id, name, nic, email, addres, Phone, dob, alres1, alres2, alres3, alrank, faculty, acayear);
        MainForm.jLabel_StdCount.setText("UG Student Count = "+Integer.toString( MyFunction.countData("undergradstd")));
        MainForm.jLabel_som.setText("SOM UG Student Count = "+Integer.toString( MyFunction.countsom("undergradstd")));
        MainForm.jLabel_soc.setText("SOC UG Student Count = "+Integer.toString( MyFunction.countsoc("undergradstd")));
        MainForm.jLabel_soe.setText("SOE UG Student Count = "+Integer.toString( MyFunction.countsoe("undergradstd")));
        manageStudentsForm.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","NIC","Email","Addres","Phone","DOB","A/L res1","A/L res2","A/L res3","A/L rank","Faculty","Aca year"}));
        std.fillStudentJtable(manageStudentsForm.jTable1, "");
        }
                
        
        
            
            
        

    }//GEN-LAST:event_jButtonAddUGStudentActionPerformed

    private void res3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res3aActionPerformed

    private void res2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res2aActionPerformed

    private void res1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res1aActionPerformed

    private void ugstdsoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdsoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdsoeActionPerformed

    private void ugstdacayearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdacayearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdacayearActionPerformed

    private void ugstdrankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdrankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdrankActionPerformed

    private void ugstdnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdnicActionPerformed

    private void ugstdaddresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdaddresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdaddresActionPerformed

    private void ugstdtpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ugstdtpKeyTyped
        // allow only numbers

        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_ugstdtpKeyTyped

    private void ugstdtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdtpActionPerformed

    }//GEN-LAST:event_ugstdtpActionPerformed

    private void ugstdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdnameActionPerformed

    private void ugstdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdidActionPerformed

    private void ugstddobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstddobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstddobActionPerformed

    private void ugstddobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ugstddobKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstddobKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Addugstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Addugstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Addugstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Addugstd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Addugstd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddUGStudent;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton res1a;
    private javax.swing.JRadioButton res1b;
    private javax.swing.JRadioButton res1c;
    private javax.swing.JRadioButton res1s;
    private javax.swing.JRadioButton res2a;
    private javax.swing.JRadioButton res2b;
    private javax.swing.JRadioButton res2c;
    private javax.swing.JRadioButton res2s;
    private javax.swing.JRadioButton res3a;
    private javax.swing.JRadioButton res3b;
    private javax.swing.JRadioButton res3c;
    private javax.swing.JRadioButton res3s;
    private javax.swing.JTextField ugstdacayear;
    private javax.swing.JTextField ugstdaddres;
    private javax.swing.JTextField ugstddob;
    private javax.swing.JTextField ugstdemail;
    private javax.swing.JTextField ugstdid;
    private javax.swing.JTextField ugstdname;
    private javax.swing.JTextField ugstdnic;
    private javax.swing.JTextField ugstdrank;
    private javax.swing.JRadioButton ugstdsoc;
    private javax.swing.JRadioButton ugstdsoe;
    private javax.swing.JRadioButton ugstdsom;
    private javax.swing.JTextField ugstdtp;
    // End of variables declaration//GEN-END:variables
}
