
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lahiru Madushan
 */
public class manageStudentsForm extends javax.swing.JFrame {

    /**
     * Creates new form manageStudentsForm
     */
    ugstudent std = new ugstudent();
    public manageStudentsForm() {
        initComponents();
        std.fillStudentJtable(jTable1, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        ugstdid = new javax.swing.JTextField();
        ugstdname = new javax.swing.JTextField();
        ugstdtp = new javax.swing.JTextField();
        ugstdaddres = new javax.swing.JTextField();
        ugstdnic = new javax.swing.JTextField();
        ugstdrank = new javax.swing.JTextField();
        ugstdacayear = new javax.swing.JTextField();
        ugstdsoc = new javax.swing.JRadioButton();
        ugstdsoe = new javax.swing.JRadioButton();
        ugstdsom = new javax.swing.JRadioButton();
        res1a = new javax.swing.JRadioButton();
        res1b = new javax.swing.JRadioButton();
        res1c = new javax.swing.JRadioButton();
        res1s = new javax.swing.JRadioButton();
        res2c = new javax.swing.JRadioButton();
        res2s = new javax.swing.JRadioButton();
        res2a = new javax.swing.JRadioButton();
        res2b = new javax.swing.JRadioButton();
        res3c = new javax.swing.JRadioButton();
        res3s = new javax.swing.JRadioButton();
        res3a = new javax.swing.JRadioButton();
        res3b = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonEditUGStudent = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        ugstdemail = new javax.swing.JTextField();
        ugstddob = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonCancel = new javax.swing.JButton();
        valtofined = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel2.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel2.setText("ID :");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setText("Full Name :");

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setText("NIC :");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("UG Student Info");

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel7.setText("Addres :");

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel8.setText("Tel No:");

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel9.setText("DOB :");

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel10.setText("A/L Res 2 :");

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel11.setText("A/L Res 1 :");

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel12.setText("A/L Res 3 :");

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel13.setText("A/L Rank :");

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel14.setText("Aca Year :");

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel15.setText("Faculty :");

        ugstdid.setBackground(new java.awt.Color(51, 255, 204));
        ugstdid.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ugstdid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdidActionPerformed(evt);
            }
        });

        ugstdname.setBackground(new java.awt.Color(51, 255, 204));
        ugstdname.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ugstdname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdnameActionPerformed(evt);
            }
        });

        ugstdtp.setBackground(new java.awt.Color(51, 255, 204));
        ugstdtp.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ugstdtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdtpActionPerformed(evt);
            }
        });
        ugstdtp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ugstdtpKeyTyped(evt);
            }
        });

        ugstdaddres.setBackground(new java.awt.Color(51, 255, 204));
        ugstdaddres.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ugstdaddres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdaddresActionPerformed(evt);
            }
        });

        ugstdnic.setBackground(new java.awt.Color(51, 255, 204));
        ugstdnic.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ugstdnic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdnicActionPerformed(evt);
            }
        });

        ugstdrank.setBackground(new java.awt.Color(51, 255, 204));
        ugstdrank.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ugstdrank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdrankActionPerformed(evt);
            }
        });

        ugstdacayear.setBackground(new java.awt.Color(51, 255, 204));
        ugstdacayear.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ugstdacayear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdacayearActionPerformed(evt);
            }
        });

        ugstdsoc.setBackground(new java.awt.Color(51, 255, 204));
        ugstdsoc.setText("SOC");

        ugstdsoe.setBackground(new java.awt.Color(51, 255, 204));
        ugstdsoe.setText("SOE");
        ugstdsoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstdsoeActionPerformed(evt);
            }
        });

        ugstdsom.setBackground(new java.awt.Color(51, 255, 204));
        ugstdsom.setText("SOM");

        res1a.setBackground(new java.awt.Color(51, 255, 204));
        res1a.setText("A");
        res1a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res1aActionPerformed(evt);
            }
        });

        res1b.setBackground(new java.awt.Color(51, 255, 204));
        res1b.setText("B");

        res1c.setBackground(new java.awt.Color(51, 255, 204));
        res1c.setText("C");

        res1s.setBackground(new java.awt.Color(51, 255, 204));
        res1s.setText("S");

        res2c.setBackground(new java.awt.Color(51, 255, 204));
        res2c.setText("C");

        res2s.setBackground(new java.awt.Color(51, 255, 204));
        res2s.setText("S");

        res2a.setBackground(new java.awt.Color(51, 255, 204));
        res2a.setText("A");
        res2a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res2aActionPerformed(evt);
            }
        });

        res2b.setBackground(new java.awt.Color(51, 255, 204));
        res2b.setText("B");

        res3c.setBackground(new java.awt.Color(51, 255, 204));
        res3c.setText("C");

        res3s.setBackground(new java.awt.Color(51, 255, 204));
        res3s.setText("S");

        res3a.setBackground(new java.awt.Color(51, 255, 204));
        res3a.setText("A");
        res3a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                res3aActionPerformed(evt);
            }
        });

        res3b.setBackground(new java.awt.Color(51, 255, 204));
        res3b.setText("B");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nsbm-green-uni-logo.png"))); // NOI18N

        jButtonEditUGStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonEditUGStudent.setText("Edit");
        jButtonEditUGStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditUGStudentActionPerformed(evt);
            }
        });

        jButtonRemove.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonRemove.setText("Remove");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel16.setText("Email :");

        ugstdemail.setBackground(new java.awt.Color(51, 255, 204));
        ugstdemail.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        ugstddob.setBackground(new java.awt.Color(51, 255, 204));
        ugstddob.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ugstddob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ugstddobActionPerformed(evt);
            }
        });
        ugstddob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ugstddobKeyTyped(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(51, 255, 204));
        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "NIC", "Email", "Addres", "Phone", "DOB", "A/L res1", "A/L res2", "A/L res3", "A/L rank", "Faculty", "Aca year"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        valtofined.setBackground(new java.awt.Color(51, 255, 204));
        valtofined.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        valtofined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valtofinedActionPerformed(evt);
            }
        });
        valtofined.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valtofinedKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valtofinedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valtofinedKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setText("Enter Value to Search :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addGap(28, 28, 28)
                        .addComponent(jButtonRemove)
                        .addGap(26, 26, 26)
                        .addComponent(jButtonEditUGStudent)
                        .addGap(75, 75, 75)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel16)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(ugstdid, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ugstdnic, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ugstdname, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(res3a)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(res3b)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(res3c)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(res3s))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(res2a)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(res2b)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(res2c)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(res2s))))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(res1a)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(res1b)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(res1c)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(res1s))
                                    .addComponent(ugstdemail, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ugstdtp, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ugstddob, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ugstdrank, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ugstdaddres, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(ugstdsoc)
                                        .addGap(18, 18, 18)
                                        .addComponent(ugstdsoe)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ugstdsom))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ugstdacayear, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valtofined, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEditUGStudent)
                            .addComponent(jButtonRemove)
                            .addComponent(jButtonCancel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ugstdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ugstdname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valtofined, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ugstdnic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ugstdemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel7)
                                            .addComponent(ugstdaddres, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel8)
                                            .addComponent(ugstdtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel9))
                                    .addComponent(ugstddob, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(res1a)
                                    .addComponent(res1b)
                                    .addComponent(res1c)
                                    .addComponent(res1s))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(res2a)
                                    .addComponent(res2b)
                                    .addComponent(res2c)
                                    .addComponent(res2s))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(res3a)
                                    .addComponent(res3b)
                                    .addComponent(res3c)
                                    .addComponent(res3s))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ugstdrank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(ugstdsoc)
                                    .addComponent(ugstdsoe)
                                    .addComponent(ugstdsom))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ugstdacayear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(59, 59, 59))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ugstdidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdidActionPerformed

    private void ugstdnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdnameActionPerformed

    private void ugstdtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdtpActionPerformed

    }//GEN-LAST:event_ugstdtpActionPerformed

    private void ugstdtpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ugstdtpKeyTyped
        // allow only numbers

        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_ugstdtpKeyTyped

    private void ugstdaddresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdaddresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdaddresActionPerformed

    private void ugstdnicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdnicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdnicActionPerformed

    private void ugstdrankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdrankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdrankActionPerformed

    private void ugstdacayearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdacayearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdacayearActionPerformed

    private void ugstdsoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstdsoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstdsoeActionPerformed

    private void res1aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res1aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res1aActionPerformed

    private void res2aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res2aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res2aActionPerformed

    private void res3aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_res3aActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_res3aActionPerformed

    public boolean verifText(){
        if(ugstdid.getText().equals("") || ugstdname.getText().equals("") || ugstdnic.getText().equals("") || ugstdemail.getText().equals("") || ugstdaddres.getText().equals("") || ugstdtp.getText().equals("") || ugstddob.getText().equals("") || ugstdrank.getText().equals("") || ugstdacayear.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Some fields are empty!!!");
            return false;
        }
        else{
            return true;
        }
    }
    
    private void jButtonEditUGStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditUGStudentActionPerformed
        
        
        String name = ugstdname.getText();
        String nic = ugstdnic.getText();
        String email = ugstdemail.getText();
        String addres = ugstdaddres.getText();
        String Phone = ugstdtp.getText();
        String dob = ugstddob.getText();
        String id = ugstdid.getText();

        String alres1 = "A";
        if(res1b.isSelected()){
            alres1 = "B";
        }else if(res1c.isSelected()){
            alres1 = "C";
        }else if(res1s.isSelected()){
            alres1 = "S";
        }

        String alres2 = "A";
        if(res2b.isSelected()){
            alres2 = "B";
        }else if(res2c.isSelected()){
            alres2 = "C";
        }else if(res2s.isSelected()){
            alres2 = "S";
        }

        String alres3 = "A";
        if(res3b.isSelected()){
            alres3 = "B";
        }else if(res3c.isSelected()){
            alres3 = "C";
        }else if(res3s.isSelected()){
            alres3 = "S";
        }

        String alrank = ugstdrank.getText();

        String faculty = "SOC";
        if(ugstdsoe.isSelected()){
            faculty = "SOE";
        }else if(ugstdsom.isSelected()){
            faculty = "SOM";
        }

        String acayear = ugstdacayear.getText();

        if(verifText()){
            ugstudent ugstd = new ugstudent();
            ugstd.insertUpdateDeleteUGStudent('u', id, name, nic, email, addres, Phone, dob, alres1, alres2, alres3, alrank, faculty, acayear);
            manageStudentsForm.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","NIC","Email","Addres","Phone","DOB","A/L res1","A/L res2","A/L res3","A/L rank","Faculty","Aca year"}));
            std.fillStudentJtable(manageStudentsForm.jTable1, "");

//MainForm.jLabel_StdCount.setText("UG Student Count = "+Integer.toString( MyFunction.countData("ugstd")));
        }

    }//GEN-LAST:event_jButtonEditUGStudentActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        if(ugstdid.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Select a student");
        }else{
        String id = String.valueOf(ugstdid.getText());
        std.insertUpdateDeleteUGStudent('d', id, null, null, null, null, null, null, null, null, null, null, null, null);
        manageStudentsForm.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","NIC","Email","Addres","Phone","DOB","Degree","Institute","Years","Faculty","Aca year"}));
        std.fillStudentJtable(manageStudentsForm.jTable1, "");
        }
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    private void ugstddobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ugstddobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstddobActionPerformed

    private void ugstddobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ugstddobKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ugstddobKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        int rowIndex = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        
        if(model.getValueAt(rowIndex, 11).toString().equals("SOC"))
        {
            ugstdsoc.setSelected(true);
            ugstdsoe.setSelected(false);
            ugstdsom.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 11).toString().equals("SOE"))
        {
            ugstdsoc.setSelected(false);
            ugstdsoe.setSelected(true);
            ugstdsom.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 11).toString().equals("SOM"))
        {
            ugstdsoc.setSelected(false);
            ugstdsoe.setSelected(false);
            ugstdsom.setSelected(true);
        }
        
        if(model.getValueAt(rowIndex, 7).toString().equals("A"))
        {
            res1a.setSelected(true);
            res1b.setSelected(false);
            res1c.setSelected(false);
            res1s.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 7).toString().equals("B"))
        {
            res1a.setSelected(false);
            res1b.setSelected(true);
            res1c.setSelected(false);
            res1s.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 7).toString().equals("C"))
        {
            res1a.setSelected(false);
            res1b.setSelected(false);
            res1c.setSelected(true);
            res1s.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 7).toString().equals("S"))
        {
            res1a.setSelected(false);
            res1b.setSelected(false);
            res1c.setSelected(false);
            res1s.setSelected(true);
        }
        
        if(model.getValueAt(rowIndex, 8).toString().equals("A"))
        {
            res2a.setSelected(true);
            res2b.setSelected(false);
            res2c.setSelected(false);
            res2s.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 8).toString().equals("B"))
        {
            res2a.setSelected(false);
            res2b.setSelected(true);
            res2c.setSelected(false);
            res2s.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 8).toString().equals("C"))
        {
            res2a.setSelected(false);
            res2b.setSelected(false);
            res2c.setSelected(true);
            res2s.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 8).toString().equals("S"))
        {
            res2a.setSelected(false);
            res2b.setSelected(false);
            res2c.setSelected(false);
            res2s.setSelected(true);
        }
        
        if(model.getValueAt(rowIndex, 9).toString().equals("A"))
        {
            res3a.setSelected(true);
            res3b.setSelected(false);
            res3c.setSelected(false);
            res3s.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 9).toString().equals("B"))
        {
            res3a.setSelected(false);
            res3b.setSelected(true);
            res3c.setSelected(false);
            res3s.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 9).toString().equals("C"))
        {
            res3a.setSelected(false);
            res3b.setSelected(false);
            res3c.setSelected(true);
            res3s.setSelected(false);
        }
        else if(model.getValueAt(rowIndex, 9).toString().equals("S"))
        {
            res3a.setSelected(false);
            res3b.setSelected(false);
            res3c.setSelected(false);
            res3s.setSelected(true);
        }
        
        ugstdid.setText(model.getValueAt(rowIndex, 0).toString());
        ugstdname.setText(model.getValueAt(rowIndex, 1).toString());
        ugstdnic.setText(model.getValueAt(rowIndex, 2).toString());
        ugstdemail.setText(model.getValueAt(rowIndex, 3).toString());
        ugstdaddres.setText(model.getValueAt(rowIndex, 4).toString());
        ugstdtp.setText(model.getValueAt(rowIndex, 5).toString());
        ugstddob.setText(model.getValueAt(rowIndex, 6).toString());
        ugstdrank.setText(model.getValueAt(rowIndex, 10).toString());
        ugstdacayear.setText(model.getValueAt(rowIndex, 12).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void valtofinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valtofinedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valtofinedActionPerformed

    private void valtofinedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valtofinedKeyTyped
        
    }//GEN-LAST:event_valtofinedKeyTyped

    private void valtofinedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valtofinedKeyPressed
//        jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","NIC","Email","Addres","Phone","DOB","A/L res1","A/L res2","A/L res3","A/L rank","Faculty","Aca year"}));
//        std.fillStudentJtable(jTable1, valtofined.getText());
    }//GEN-LAST:event_valtofinedKeyPressed

    private void valtofinedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valtofinedKeyReleased
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","NIC","Email","Addres","Phone","DOB","A/L res1","A/L res2","A/L res3","A/L rank","Faculty","Aca year"}));
        std.fillStudentJtable(jTable1, valtofined.getText());
    }//GEN-LAST:event_valtofinedKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageStudentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageStudentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonEditUGStudent;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JRadioButton res1a;
    private javax.swing.JRadioButton res1b;
    private javax.swing.JRadioButton res1c;
    private javax.swing.JRadioButton res1s;
    private javax.swing.JRadioButton res2a;
    private javax.swing.JRadioButton res2b;
    private javax.swing.JRadioButton res2c;
    private javax.swing.JRadioButton res2s;
    private javax.swing.JRadioButton res3a;
    private javax.swing.JRadioButton res3b;
    private javax.swing.JRadioButton res3c;
    private javax.swing.JRadioButton res3s;
    private javax.swing.JTextField ugstdacayear;
    private javax.swing.JTextField ugstdaddres;
    private javax.swing.JTextField ugstddob;
    private javax.swing.JTextField ugstdemail;
    private javax.swing.JTextField ugstdid;
    private javax.swing.JTextField ugstdname;
    private javax.swing.JTextField ugstdnic;
    private javax.swing.JTextField ugstdrank;
    private javax.swing.JRadioButton ugstdsoc;
    private javax.swing.JRadioButton ugstdsoe;
    private javax.swing.JRadioButton ugstdsom;
    private javax.swing.JTextField ugstdtp;
    private javax.swing.JTextField valtofined;
    // End of variables declaration//GEN-END:variables
}
