
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lahiru Madushan
 */
public class Sendrespg extends javax.swing.JFrame {

    /**
     * Creates new form Sendrespg
     */
    result res = new result();
    public Sendrespg() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        sender = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jButtonCancel = new javax.swing.JButton();
        valtofined = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rs1 = new javax.swing.JTextField();
        rs1su = new javax.swing.JTextField();
        rs2su = new javax.swing.JTextField();
        rs2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rs3 = new javax.swing.JTextField();
        rs3su = new javax.swing.JTextField();
        rs4su = new javax.swing.JTextField();
        rs4 = new javax.swing.JTextField();
        rs5 = new javax.swing.JTextField();
        rs5su = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        rs6 = new javax.swing.JTextField();
        rs6su = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        index = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        email = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 255, 204));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Send PG Result");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/nsbm-green-uni-logo.png"))); // NOI18N

        sender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sender.setText("Send");
        sender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderActionPerformed(evt);
            }
        });

        jTable.setBackground(new java.awt.Color(51, 255, 204));
        jTable.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Email"
            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        valtofined.setBackground(new java.awt.Color(51, 255, 204));
        valtofined.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        valtofined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valtofinedActionPerformed(evt);
            }
        });
        valtofined.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                valtofinedKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                valtofinedKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                valtofinedKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel5.setText("Student Index :");

        jTable1.setBackground(new java.awt.Color(51, 255, 204));
        jTable1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Sub1", "Result", "Sub2", "Result", "Sub3", "Result", "Sub4", "Result", "Sub5", "Result", "Sub6", "Result"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel12.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel12.setText("Result");

        jLabel9.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel9.setText("Subject");

        jLabel3.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel3.setText("Subject 1 :");

        rs1.setBackground(new java.awt.Color(51, 255, 204));
        rs1.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs1ActionPerformed(evt);
            }
        });

        rs1su.setBackground(new java.awt.Color(51, 255, 204));
        rs1su.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs1su.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rs1suMouseClicked(evt);
            }
        });
        rs1su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs1suActionPerformed(evt);
            }
        });

        rs2su.setBackground(new java.awt.Color(51, 255, 204));
        rs2su.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs2su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs2suActionPerformed(evt);
            }
        });

        rs2.setBackground(new java.awt.Color(51, 255, 204));
        rs2.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel6.setText("Subject 2 :");

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel7.setText("Subject 3 :");

        rs3.setBackground(new java.awt.Color(51, 255, 204));
        rs3.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs3ActionPerformed(evt);
            }
        });

        rs3su.setBackground(new java.awt.Color(51, 255, 204));
        rs3su.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs3su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs3suActionPerformed(evt);
            }
        });

        rs4su.setBackground(new java.awt.Color(51, 255, 204));
        rs4su.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs4su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs4suActionPerformed(evt);
            }
        });

        rs4.setBackground(new java.awt.Color(51, 255, 204));
        rs4.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs4ActionPerformed(evt);
            }
        });

        rs5.setBackground(new java.awt.Color(51, 255, 204));
        rs5.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        rs5su.setBackground(new java.awt.Color(51, 255, 204));
        rs5su.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs5su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs5suActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel10.setText("Subject 5 :");

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel11.setText("Subject 6 :");

        rs6.setBackground(new java.awt.Color(51, 255, 204));
        rs6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N

        rs6su.setBackground(new java.awt.Color(51, 255, 204));
        rs6su.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        rs6su.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rs6suActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel8.setText("Subject 4 :");

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel13.setText("Index :");

        jLabel14.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel14.setText("Name :");

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 1, 14)); // NOI18N
        jLabel15.setText("Email :");

        index.setBackground(new java.awt.Color(51, 255, 204));
        index.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        index.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexActionPerformed(evt);
            }
        });

        name.setBackground(new java.awt.Color(51, 255, 204));
        name.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        email.setBackground(new java.awt.Color(51, 255, 204));
        email.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancel)
                        .addGap(37, 37, 37)
                        .addComponent(sender))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(index, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                            .addComponent(email))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(rs6)
                    .addComponent(rs5)
                    .addComponent(rs4)
                    .addComponent(rs3)
                    .addComponent(rs2)
                    .addComponent(rs1)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rs5su, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rs4su, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rs3su, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rs2su, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rs1su, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rs6su, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(352, 352, 352))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(valtofined, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valtofined, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rs1su, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel13)
                            .addComponent(index, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rs2su, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel14)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rs3su, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rs4su, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rs5su, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rs6su, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCancel)
                            .addComponent(sender)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rs1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rs2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rs3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rs4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rs5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rs6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderActionPerformed
        String ID = index.getText();
        String Name = name.getText();
        String Email = email.getText();
        String S1 = rs1.getText();
        String S1s = rs1su.getText();
        String S2 = rs2.getText();
        String S2s = rs2su.getText();
        String S3 = rs3.getText();
        String S3s = rs3su.getText();
        String S4 = rs4.getText();
        String S4s = rs4su.getText();
        String S5 = rs5.getText();
        String S5s = rs5su.getText();
        String S6 = rs6.getText();
        String S6s = rs6su.getText();

        SendMail se = new SendMail();
        SendMail.mail(ID,Name,Email,S1,S1s,S2,S2s,S3,S3s,S4,S4s,S5,S5s,S6,S6s);
    }//GEN-LAST:event_senderActionPerformed

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked

        int rowIndex = jTable.getSelectedRow();
        DefaultTableModel model2 = (DefaultTableModel)jTable.getModel();

        index.setText(model2.getValueAt(rowIndex, 0).toString());
        name.setText(model2.getValueAt(rowIndex, 1).toString());
        email.setText(model2.getValueAt(rowIndex, 2).toString());

    }//GEN-LAST:event_jTableMouseClicked

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void valtofinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valtofinedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valtofinedActionPerformed

    private void valtofinedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valtofinedKeyPressed
        //        jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID","Name","NIC","Email","Addres","Phone","DOB","A/L res1","A/L res2","A/L res3","A/L rank","Faculty","Aca year"}));
        //        std.fillStudentJtable(jTable1, valtofined.getText());
    }//GEN-LAST:event_valtofinedKeyPressed

    private void valtofinedKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valtofinedKeyReleased
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID","Sub1","Result","Sub2","Result","Sub3","Result","Sub4","Result","Sub5","Result","Sub6","Result"}));
        res.fillResultJtable(jTable1, valtofined.getText());

        jTable.setModel(new DefaultTableModel(null, new Object[]{"Index","Name","Email"}));
        res.fillIndexpgJtable(jTable, valtofined.getText());

    }//GEN-LAST:event_valtofinedKeyReleased

    private void valtofinedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_valtofinedKeyTyped

    }//GEN-LAST:event_valtofinedKeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

        int rowIndex = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();

        rs1.setText(model.getValueAt(rowIndex, 1).toString());
        rs1su.setText(model.getValueAt(rowIndex, 2).toString());
        rs2.setText(model.getValueAt(rowIndex, 3).toString());
        rs2su.setText(model.getValueAt(rowIndex, 4).toString());
        rs3.setText(model.getValueAt(rowIndex, 5).toString());
        rs3su.setText(model.getValueAt(rowIndex, 6).toString());
        rs4.setText(model.getValueAt(rowIndex, 7).toString());
        rs4su.setText(model.getValueAt(rowIndex, 8).toString());
        rs5.setText(model.getValueAt(rowIndex, 9).toString());
        rs5su.setText(model.getValueAt(rowIndex, 10).toString());
        rs6.setText(model.getValueAt(rowIndex, 11).toString());
        rs6su.setText(model.getValueAt(rowIndex, 12).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void rs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs1ActionPerformed

    private void rs1suMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rs1suMouseClicked

    }//GEN-LAST:event_rs1suMouseClicked

    private void rs1suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs1suActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs1suActionPerformed

    private void rs2suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs2suActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs2suActionPerformed

    private void rs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs2ActionPerformed

    private void rs3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs3ActionPerformed

    private void rs3suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs3suActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs3suActionPerformed

    private void rs4suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs4suActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs4suActionPerformed

    private void rs4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs4ActionPerformed

    private void rs5suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs5suActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs5suActionPerformed

    private void rs6suActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rs6suActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rs6suActionPerformed

    private void indexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sendrespg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sendrespg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sendrespg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sendrespg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sendrespg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField email;
    private javax.swing.JTextField index;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable jTable;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField rs1;
    private javax.swing.JTextField rs1su;
    private javax.swing.JTextField rs2;
    private javax.swing.JTextField rs2su;
    private javax.swing.JTextField rs3;
    private javax.swing.JTextField rs3su;
    private javax.swing.JTextField rs4;
    private javax.swing.JTextField rs4su;
    private javax.swing.JTextField rs5;
    private javax.swing.JTextField rs5su;
    private javax.swing.JTextField rs6;
    private javax.swing.JTextField rs6su;
    private javax.swing.JButton sender;
    private javax.swing.JTextField valtofined;
    // End of variables declaration//GEN-END:variables
}
